package ca.weblite.iosnativetest;

import static com.codename1.ui.CN.*;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;
import com.codenameone.ios.foundation.NSURLSession;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class IOSNativeTest extends Lifecycle {
    private TextArea textArea;
    private TextField urlField;

    @Override
    public void runApp() {
        Form hi = new Form("Hi World", new BorderLayout());
        textArea = new TextArea();
        urlField = new TextField();
        urlField.setText("https://start.codenameone.com/images/codenameone-logo.svg");
        hi.add(BorderLayout.NORTH, urlField);
        hi.add(BorderLayout.CENTER, textArea);
        Button fetch = new Button("Fetch URL");
        fetch.addActionListener(evt->testNSURLSession());
        hi.add(BorderLayout.SOUTH, fetch);
        hi.show();
    }



    private void testNSURLSession() {
        if (!NSURLSession.isSupported()) {
            
            Dialog.show("Not supported", "NSURLSession not supported on this platform", "OK", null);
            return;
        }
        NSURLSession.getSharedSession().downloadTaskWithURL(urlField.getText()).ready(task-> {
            File location = task.getLocation();
            try {
                String contents = Util.readToString(location);
                callSerially(()->{
                    textArea.setText(contents);
                    textArea.getParent().revalidateWithAnimationSafety();
                });
            } catch (Exception ex) {
                callSerially(()->{
                    textArea.setText(ex.getMessage());
                    textArea.getParent().revalidateWithAnimationSafety();
                });
            }
        }).except(ex->{
            callSerially(()->{
                textArea.setText(ex.getMessage());
                textArea.getParent();
            });
        });

    }

}
